apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: voce
  name: voce
spec:
  ports:
  - name: "80"
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: voce
  type: NodePort
