apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: vote-options
    envs:
      - options.env
replicas:
  - name: vote
    count: 3
images:
  - name: schoolofdevops/vote
    newTag: main-ea62c425-1623341815 # {"$imagepolicy": "flux-system:vote:tag"}
