apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labes:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 3
  template:
    spec:
      $setElementOrder/containers:
      - name: vote
      containers:
      - image: shcoolofdevops/vote:v4
        name: vote
